networks:
  lnnet:

services:
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: lnbook/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always

  Alice:
    container_name: Alice
    depends_on:
      - bitcoind
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Bob:
    container_name: Bob
    depends_on:
      - bitcoind    
    build:
      context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9736:9735"
    restart: always

  Chan:
    container_name: Chan
    depends_on:
      - bitcoind    
    build:
        context: c-lightning
    image: lnbook/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9737:9735"
    restart: always

  Dina:
    container_name: Dina
    depends_on:
      - bitcoind    
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9738:9735"
    restart: always
